[package]
name = "hexthing-gfxrs"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[features]
default = []
metal = ["gfx-backend-metal"]
gl = ["gfx-backend-gl"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
env_logger = "^0.5"
log = "^0.4"
winit = "^0.17"
glsl-to-spirv = "^0.1.4"
gfx = "^0.17.1"
gfx-hal = { path = "../gfx/src/hal", version = "0.1" }
gfx-backend-empty = { path = "../gfx/src/backend/empty", version = "0.1" }

[dependencies.gfx-backend-gl]
path = "../gfx/src/backend/gl"
version = "^0.1"
features = ["glutin"]
optional = true

[dependencies.gfx-backend-vulkan]
path = "../gfx/src/backend/vulkan"
version = "^0.1"
#features = ["glsl-to-spirv"]
optional = true

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies.gfx-backend-metal]
path = "../gfx/src/backend/metal"
version = "^0.1"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
path = "../gfx/src/backend/dx12"
version = "^0.1"
optional = true
